title: "My Engineering Log"
content_dir: "./assets/entries"

template_dir: "./assets/templates"
page_template: "page.html"
index_template: "index.html"
tags_template: "tags.html"

output_dir: "./dist"
server_port: 8080